# Get common recipes
recipes = ENV['fsa'] + '/PlotTools/rake/recipes.rake'
import recipes

$jobid = ENV['jobid']

# Figure out what run period we are in
$period = '8TeV'
PU = ENV['PU']
#if $jobid.include? '8TeV'
#  $period = '8TeV'
#end


################################################################################
## Sample names ################################################################
################################################################################
#
# Get sample names containing a substring
def get_sample_names(substring)
  inputs = Dir.glob("inputs/#{$jobid}/*.txt").select {|x| x.include? substring}
  inputs = inputs.map{|x| File.basename(x).sub(".txt", "")}
  return inputs
end
#
samples = Hash[
  "Singlet" => get_sample_names('ST_t'),
  "HiggsGG" => get_sample_names('GluGlu'),
  "HiggsVBF" => get_sample_names('VBF'),
  "TTBar" =>  get_sample_names('TT_TuneCUETP8M1_13TeV-powheg-pythia8'),
  "WJets" =>  get_sample_names('WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8'),
  "DYZeroJets" =>  get_sample_names('DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "DYAmcJets" => Array['DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8'],
  "DYJets" => Array['DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'],
  "DYJetsRedo2To4" => Array['DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'],
  "ZTauTauJets" => Array['ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'],
  "ZTauTauJetsRedo2To4" => Array['ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'],
  #"ZTauTauZeroJets" => get_sample_names('ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "ZTauTauAmcJets" => Array['ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8'],
  "SMHiggs" =>  Array['GluGluToHToTauTau_M-125_13TeV-powheg-pythia6','VBF_HToTauTau_M-125_13TeV-powheg-pythia6'],
  "SingleTop" => get_sample_names('ST'),
  #"DiBoson" => Array['WWTo2L2Nu_13TeV-powheg','WZ_TuneCUETP8M1_13TeV-pythia8','ZZ_TuneCUETP8M1_13TeV-pythia8']
  "DiBoson" => Array['WW_TuneCUETP8M1_13TeV-pythia8','WZ_TuneCUETP8M1_13TeV-pythia8','ZZ_TuneCUETP8M1_13TeV-pythia8'],
  "Data2016C" => get_sample_names('data_SingleMuon_Run2016C'),
  "Data2016D" => get_sample_names('data_SingleMuon_Run2016D'),
  "DataSingleE" =>get_sample_names('SingleElectron'),
  "DataSingleMuon" =>get_sample_names('SingleMuon')
]

# Function to get the .root files for an analyzer and samples
def get_analyzer_results(analyzer, the_samples)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
  the_samples.each do |sample|
    output << "results/#{$jobid}/#{analyzer_base}/#{sample}.root"
  end
  return output
end

################################################################################
## Recipes to analyze the GG channel of the LFV HToMuTau analysis
##  targets:
##     mt
################################################################################

##use $PU = false for samples with no pileup
task :analyze2016Misc => get_analyzer_results( "AnalyzeLFVMuTau.py",samples['DiBoson']+samples['TTBar']+samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016MiscNoTTBar => get_analyzer_results( "AnalyzeLFVMuTau.py",samples['DiBoson']+samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016Singlet => get_analyzer_results( "AnalyzeLFVMuTau.py",samples['Singlet'])
task :analyze2016WJets => get_analyzer_results("AnalyzeLFVMuTau.py",samples['WJets'])
task :analyze2016ZJets => get_analyzer_results("AnalyzeLFVMuTau.py",samples['DYJets'])
task :analyze2016mmtZJets => get_analyzer_results("AnalyzeLFVMuMuTau.py",samples['DYJets'])
task :analyze2016eetZJets => get_analyzer_results("AnalyzeLFVEETau.py",samples['DYJets'])
task :analyze2016eemZJets => get_analyzer_results("AnalyzeLFVEEMu.py",samples['DYJets'])
task :analyze2016eemDiBoson => get_analyzer_results("AnalyzeLFVEEMu.py",samples['DiBoson'])
task :analyze2016eemDataSingleE => get_analyzer_results("AnalyzeLFVEEMu.py",samples['DataSingleE'])
task :analyze2016mmmZJets => get_analyzer_results("AnalyzeLFVMuMuMu.py",samples['DYJets'])
task :analyze2016mmmDiBoson => get_analyzer_results("AnalyzeLFVMuMuMu.py",samples['DiBoson'])
task :analyze2016mmmDataSingleMuon => get_analyzer_results("AnalyzeLFVMuMuMu.py",samples['DataSingleMuon'])
task :analyze2016DYAmcJets => get_analyzer_results("AnalyzeLFVMuTau.py",samples['DYAmcJets'])
task :analyze2016TTBar => get_analyzer_results("AnalyzeLFVMuTau.py",samples['TTBar'])
task :analyze2016Higgs => get_analyzer_results("AnalyzeLFVMuTau.py",samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016ZTauTauJets => get_analyzer_results("AnalyzeLFVMuTau.py",samples['ZTauTauJets'])
task :analyze2016ZTauTauAmcJets => get_analyzer_results("AnalyzeLFVMuTau.py",samples['ZTauTauAmcJets'])
task :analyzeLFVMuTauData => get_analyzer_results( "AnalyzeLFVMuTau.py",samples['Data2016C']+samples['Data2016D'])
task :analyze2016MiscSignal => get_analyzer_results( "AnalyzeLFVMuTauSignal.py",samples['SingleTop']+samples['DiBoson']+samples['TTBar']+samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016WJetsSignal => get_analyzer_results("AnalyzeLFVMuTauSignal.py",samples['WJets'])
task :analyze2016ZJetsSignal => get_analyzer_results("AnalyzeLFVMuTauSignal.py",samples['DYJets'])
task :analyzeLFVMuTauDataSignal => get_analyzer_results( "AnalyzeLFVMuTauSignal.py",samples['Data2016C']+samples['Data2016D'])
task :analyzeLFVMuMuTau => get_analyzer_results("AnalyzeLFVMuMuTau.py", samples['DYJets'])
task :analyzeLFVMuMuTauData => get_analyzer_results( "AnalyzeLFVMuMuTau.py",samples['Data2016C']+samples['Data2016D'])
task :analyzeLFVMuMu => get_analyzer_results("AnalyzeLFVMuMu.py", samples['DYJets'])
task :analyzeLFVMuMuData => get_analyzer_results( "AnalyzeLFVMuMu.py",samples['Data2016C']+samples['Data2016D'])

#systematics
task :analyze2016MiscJesUp => get_analyzer_results( "AnalyzeLFVMuTaujesup.py",samples['DiBoson']+samples['TTBar']+samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016SingletJesUp => get_analyzer_results( "AnalyzeLFVMuTaujesup.py",samples['Singlet'])
task :analyze2016WJetsJesUp => get_analyzer_results("AnalyzeLFVMuTaujesup.py",samples['WJets'])
task :analyze2016ZJetsJesUp => get_analyzer_results("AnalyzeLFVMuTaujesup.py",samples['DYJets'])
task :analyze2016ZTauTauJetsJesUp => get_analyzer_results("AnalyzeLFVMuTaujesup.py",samples['ZTauTauJets'])
task :analyze2016DYJetsRedo2To4JesUp => get_analyzer_results("AnalyzeLFVMuTaujesup.py",samples['DYJetsRedo2To4'])
task :analyze2016ZTauTauAmcJetsJesUp => get_analyzer_results("AnalyzeLFVMuTaujesup.py",samples['ZTauTauAmcJets'])
task :analyze2016DYAmcJetsJesUp => get_analyzer_results("AnalyzeLFVMuTaujesup.py",samples['DYAmcJets'])
task :analyze2016TTBarJesUp => get_analyzer_results("AnalyzeLFVMuTaujesup.py",samples['TTBar'])
task :analyze2016HiggsJesUp => get_analyzer_results("AnalyzeLFVMuTaujesup.py",samples['HiggsGG']+samples['HiggsVBF'])
task :analyzeLFVMuTauDataJesUp => get_analyzer_results( "AnalyzeLFVMuTaujesup.py",samples['Data2016C']+samples['Data2016D'])

task :analyze2016MiscJesDown => get_analyzer_results( "AnalyzeLFVMuTaujesdown.py",samples['DiBoson']+samples['TTBar']+samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016SingletJesDown => get_analyzer_results( "AnalyzeLFVMuTaujesdown.py",samples['Singlet'])
task :analyze2016WJetsJesDown => get_analyzer_results("AnalyzeLFVMuTaujesdown.py",samples['WJets'])
task :analyze2016ZJetsJesDown => get_analyzer_results("AnalyzeLFVMuTaujesdown.py",samples['DYJets'])
task :analyze2016TTBarJesDown => get_analyzer_results("AnalyzeLFVMuTaujesdown.py",samples['TTBar'])
task :analyze2016HiggsJesDown => get_analyzer_results("AnalyzeLFVMuTaujesdown.py",samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016ZTauTauJetsJesDown => get_analyzer_results("AnalyzeLFVMuTaujesdown.py",samples['ZTauTauJets'])
task :analyze2016ZTauTauAmcJetsJesDown => get_analyzer_results("AnalyzeLFVMuTaujesdown.py",samples['ZTauTauAmcJets'])
task :analyze2016DYAmcJetsJesDown => get_analyzer_results("AnalyzeLFVMuTaujesdown.py",samples['DYAmcJets'])
task :analyzeLFVMuTauDataJesDown => get_analyzer_results( "AnalyzeLFVMuTaujesdown.py",samples['Data2016C']+samples['Data2016D'])

task :analyze2016MiscUesUp => get_analyzer_results( "AnalyzeLFVMuTauuesup.py",samples['DiBoson']+samples['TTBar']+samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016SingletUesUp => get_analyzer_results( "AnalyzeLFVMuTauuesup.py",samples['Singlet'])
task :analyze2016WJetsUesUp => get_analyzer_results("AnalyzeLFVMuTauuesup.py",samples['WJets'])
task :analyze2016ZJetsUesUp => get_analyzer_results("AnalyzeLFVMuTauuesup.py",samples['DYJets'])
task :analyze2016ZTauTauJetsUesUp => get_analyzer_results("AnalyzeLFVMuTauuesup.py",samples['ZTauTauJets'])
task :analyze2016ZTauTauJetsRedo2To4UesUp => get_analyzer_results("AnalyzeLFVMuTauuesup.py",samples['ZTauTauJetsRedo2To4'])
task :analyze2016DYJetsRedo2To4UesUp => get_analyzer_results("AnalyzeLFVMuTauuesup.py",samples['DYJetsRedo2To4'])
task :analyze2016ZTauTauAmcJetsUesUp => get_analyzer_results("AnalyzeLFVMuTauuesup.py",samples['ZTauTauAmcJets'])
task :analyze2016DYAmcJetsUesUp => get_analyzer_results("AnalyzeLFVMuTauuesup.py",samples['DYAmcJets'])
task :analyze2016TTBarUesUp => get_analyzer_results("AnalyzeLFVMuTauuesup.py",samples['TTBar'])
task :analyze2016HiggsUesUp => get_analyzer_results("AnalyzeLFVMuTauuesup.py",samples['HiggsGG']+samples['HiggsVBF'])
task :analyzeLFVMuTauDataUesUp => get_analyzer_results( "AnalyzeLFVMuTauuesup.py",samples['Data2016C']+samples['Data2016D'])

task :analyze2016MiscUesDown => get_analyzer_results( "AnalyzeLFVMuTauuesdown.py",samples['DiBoson']+samples['TTBar']+samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016SingletUesDown => get_analyzer_results( "AnalyzeLFVMuTauuesdown.py",samples['Singlet'])
task :analyze2016WJetsUesDown => get_analyzer_results("AnalyzeLFVMuTauuesdown.py",samples['WJets'])
task :analyze2016ZJetsUesDown => get_analyzer_results("AnalyzeLFVMuTauuesdown.py",samples['DYJets'])
task :analyze2016TTBarUesDown => get_analyzer_results("AnalyzeLFVMuTauuesdown.py",samples['TTBar'])
task :analyze2016HiggsUesDown => get_analyzer_results("AnalyzeLFVMuTauuesdown.py",samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016ZTauTauJetsUesDown => get_analyzer_results("AnalyzeLFVMuTauuesdown.py",samples['ZTauTauJets'])
task :analyze2016ZTauTauAmcJetsUesDown => get_analyzer_results("AnalyzeLFVMuTauuesdown.py",samples['ZTauTauAmcJets'])
task :analyze2016DYAmcJetsUesDown => get_analyzer_results("AnalyzeLFVMuTauuesdown.py",samples['DYAmcJets'])
task :analyzeLFVMuTauDataUesDown => get_analyzer_results( "AnalyzeLFVMuTauuesdown.py",samples['Data2016C']+samples['Data2016D'])

task :analyze2016MiscTesUp => get_analyzer_results( "AnalyzeLFVMuTautesup.py",samples['DiBoson']+samples['TTBar']+samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016SingletTesUp => get_analyzer_results( "AnalyzeLFVMuTautesup.py",samples['Singlet'])
task :analyze2016WJetsTesUp => get_analyzer_results("AnalyzeLFVMuTautesup.py",samples['WJets'])
task :analyze2016ZJetsTesUp => get_analyzer_results("AnalyzeLFVMuTautesup.py",samples['DYJets'])
task :analyze2016ZTauTauJetsTesUp => get_analyzer_results("AnalyzeLFVMuTautesup.py",samples['ZTauTauJets'])
task :analyze2016ZTauTauAmcJetsTesUp => get_analyzer_results("AnalyzeLFVMuTautesup.py",samples['ZTauTauAmcJets'])
task :analyze2016ZTauTauJetsRedo2To4TesUp => get_analyzer_results("AnalyzeLFVMuTautesup.py",samples['ZTauTauJetsRedo2To4'])
task :analyze2016DYJetsRedo2To4TesUp => get_analyzer_results("AnalyzeLFVMuTautesup.py",samples['DYJetsRedo2To4'])
task :analyze2016DYAmcJetsTesUp => get_analyzer_results("AnalyzeLFVMuTautesup.py",samples['DYAmcJets'])
task :analyze2016TTBarTesUp => get_analyzer_results("AnalyzeLFVMuTautesup.py",samples['TTBar'])
task :analyze2016HiggsTesUp => get_analyzer_results("AnalyzeLFVMuTautesup.py",samples['HiggsGG']+samples['HiggsVBF'])
task :analyzeLFVMuTauDataTesUp => get_analyzer_results( "AnalyzeLFVMuTautesup.py",samples['Data2016C']+samples['Data2016D'])

task :analyze2016MiscTesDown => get_analyzer_results( "AnalyzeLFVMuTautesdown.py",samples['DiBoson']+samples['TTBar']+samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016SingletTesDown => get_analyzer_results( "AnalyzeLFVMuTautesdown.py",samples['Singlet'])
task :analyze2016WJetsTesDown => get_analyzer_results("AnalyzeLFVMuTautesdown.py",samples['WJets'])
task :analyze2016ZJetsTesDown => get_analyzer_results("AnalyzeLFVMuTautesdown.py",samples['DYJets'])
task :analyze2016TTBarTesDown => get_analyzer_results("AnalyzeLFVMuTautesdown.py",samples['TTBar'])
task :analyze2016HiggsTesDown => get_analyzer_results("AnalyzeLFVMuTautesdown.py",samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016ZTauTauJetsTesDown => get_analyzer_results("AnalyzeLFVMuTautesdown.py",samples['ZTauTauJets'])
task :analyze2016ZTauTauAmcJetsTesDown => get_analyzer_results("AnalyzeLFVMuTautesdown.py",samples['ZTauTauAmcJets'])
task :analyze2016DYAmcJetsTesDown => get_analyzer_results("AnalyzeLFVMuTautesdown.py",samples['DYAmcJets'])
task :analyzeLFVMuTauDataTesDown => get_analyzer_results( "AnalyzeLFVMuTautesdown.py",samples['Data2016C']+samples['Data2016D'])

task :analyze2016MiscFakesUp => get_analyzer_results( "AnalyzeLFVMuTaufakesup.py",samples['DiBoson']+samples['TTBar']+samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016SingletFakesUp => get_analyzer_results( "AnalyzeLFVMuTaufakesup.py",samples['Singlet'])
task :analyze2016WJetsFakesUp => get_analyzer_results("AnalyzeLFVMuTaufakesup.py",samples['WJets'])
task :analyze2016ZJetsFakesUp => get_analyzer_results("AnalyzeLFVMuTaufakesup.py",samples['DYJets'])
task :analyze2016ZTauTauJetsFakesUp => get_analyzer_results("AnalyzeLFVMuTaufakesup.py",samples['ZTauTauJets'])
task :analyze2016ZTauTauAmcJetsFakesUp => get_analyzer_results("AnalyzeLFVMuTaufakesup.py",samples['ZTauTauAmcJets'])
task :analyze2016DYAmcJetsFakesUp => get_analyzer_results("AnalyzeLFVMuTaufakesup.py",samples['DYAmcJets'])
task :analyze2016TTBarFakesUp => get_analyzer_results("AnalyzeLFVMuTaufakesup.py",samples['TTBar'])
task :analyze2016HiggsFakesUp => get_analyzer_results("AnalyzeLFVMuTaufakesup.py",samples['HiggsGG']+samples['HiggsVBF'])
task :analyzeLFVMuTauDataFakesUp => get_analyzer_results( "AnalyzeLFVMuTaufakesup.py",samples['Data2016C']+samples['Data2016D'])

task :analyze2016MiscFakesDown => get_analyzer_results( "AnalyzeLFVMuTaufakesdown.py",samples['DiBoson']+samples['TTBar']+samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016SingletFakesDown => get_analyzer_results( "AnalyzeLFVMuTaufakesdown.py",samples['Singlet'])
task :analyze2016WJetsFakesDown => get_analyzer_results("AnalyzeLFVMuTaufakesdown.py",samples['WJets'])
task :analyze2016ZJetsFakesDown => get_analyzer_results("AnalyzeLFVMuTaufakesdown.py",samples['DYJets'])
task :analyze2016TTBarFakesDown => get_analyzer_results("AnalyzeLFVMuTaufakesdown.py",samples['TTBar'])
task :analyze2016HiggsFakesDown => get_analyzer_results("AnalyzeLFVMuTaufakesdown.py",samples['HiggsGG']+samples['HiggsVBF'])
task :analyze2016ZTauTauJetsFakesDown => get_analyzer_results("AnalyzeLFVMuTaufakesdown.py",samples['ZTauTauJets'])
task :analyze2016ZTauTauAmcJetsFakesDown => get_analyzer_results("AnalyzeLFVMuTaufakesdown.py",samples['ZTauTauAmcJets'])
task :analyze2016DYAmcJetsFakesDown => get_analyzer_results("AnalyzeLFVMuTaufakesdown.py",samples['DYAmcJets'])
task :analyzeLFVMuTauDataFakesDown => get_analyzer_results( "AnalyzeLFVMuTaufakesdown.py",samples['Data2016C']+samples['Data2016D'])
#task :analyzetest2  => get_analyzer_results(  "AnalyzeLFVMuTauLoose.py",samples['signal'])
#task :analyzetest2Bg  => get_analyzer_results(  "AnalyzeLFVMuTauLoose.py",samples['TTBar']+samples['WJets']+samples['DYJets']+samples['SMHiggs'])

