set -o nounset
set -o errexit

#export jobid=MuTauSingleMuJetReRecoJes
export jobid=GT27
export Ztt=false
export embed=false
export treeSkim=false
export otherJets=false
export looseIso=false
#export jobid=dataJes
export PU=true
export iso=true
export optimized=true
export wjets=true
export NUP5=false
export selection="signal"
export jetcorrection="jesminus"
#rake mttightwjetsjes
export wjets=false
echo $selection
#rake mttightjes
rake mttightgt
#rake mttightjesMoreStats
#rake mttightSingletJes
#rake mttightRedoFakesJes
export PU=false
#rake pu1mttightjes
export PU=true
export Ztt=true
#rake DYmttightjes
export NUP5=true
#rake mttightjesZjetsM50
export Ztt=false
#rake mttightjesWjetsFiltered
export Ztt=true
export otherJets=true
#rake mttightjesotherM50
#rake zjetsmttightjes
export NUP5=false
#rake mttightjesotherDY
#rake DYmttightjes
export Ztt=false
export embed=false
export treeSkim=false
export otherJets=false
#export jobid=dataJes
export PU=true
export iso=true
export optimized=true
export wjets=true
export NUP5=false
export selection="signal"
export jetcorrection="none"
#rake mttightwjetsjes
export wjets=false
echo $selection
#rake mttightjes
rake mttightgt
#rake mttightSingletJes
#rake mttightRedoFakesJes
export PU=false
#rake pu1mttightjes
export PU=true
export Ztt=true
#rake DYmttightjes
export NUP5=true
#rake mttightjesZjetsM50
export Ztt=false
#rake mttightjesWjetsFiltered
export Ztt=true
export otherJets=true
#rake mttightjesotherM50
#rake zjetsmttightjes
export NUP5=false
#rake mttightjesotherDY
#rake DYmttightjes
export Ztt=false
export embed=false
export treeSkim=false
export otherJets=false
#export jobid=dataJes
export PU=true
export iso=true
export optimized=true
export wjets=true
export NUP5=false
export selection="signal"
export jetcorrection="jesplus"
#rake mttightwjetsjes
export wjets=false
echo $selection
#rake mttightjes
rake mttightgt
#rake mttightjesMoreStats
#rake mttightSingletJes
#rake mttightRedoFakesJes
export PU=false
#rake pu1mttightjes
export PU=true
export Ztt=true
#rake DYmttightjes
export NUP5=true
#rake mttightjesZjetsM50
export Ztt=false
#rake mttightjesWjetsFiltered
export Ztt=true
export otherJets=true
#rake mttightjesotherM50
#rake zjetsmttightjes
export NUP5=false
#rake mttightjesotherDY
#rake DYmttightjes

